version: "3"
services:
  axon-server:
    image: axoniq/axonserver
    ports:
      - "8024:8024"
      - "8124:8124"
    volumes:
      - axon-server-data:/data
      - axon-server-events:/eventdata
    environment:
      - AXONIQ_AXONSERVER_NAME=My Axon Server
      - AXONIQ_AXONSERVER_HOSTNAME=localhost
      - AXONIQ_AXONSERVER_DEVMODE_ENABLED=true

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init-postgres.sh:/docker-entrypoint-initdb.d/init-postgres.sh
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=edd
      - POSTGRES_PASSWORD=secret
      - POSTGRES_MULTIPLE_DATABASES=products,orders

volumes:
  axon-server-data:
  axon-server-events:
  postgres:
