### Get Products
GET http://localhost:8082/product-service/products
Accept: application/json

<> 2022-04-17T185620.200.json

### Create Product
POST http://localhost:8082/product-service/products
Content-Type: application/json

{
  "title":  "iPhone 12",
  "price":450,
  "quantity":3
}

<> 2022-05-22T232514.500.json
<> 2022-05-22T232321.500.json
<> 2022-05-22T215601.500.json
